name: ubuntu-resolute64

on:
  workflow_dispatch: 

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: x86_64
      compat-distro: ubuntu
      compat-distro-version: resolute64
      kernel: ubuntu-noble # Updates the build system to fetch Kernel 7.0 sources
      artifact: ${{ github.workflow }}-${{ github.run_number }}
      retention: 16
      runner: 'ubuntu-latest' 
